name: "baekjoon-bot-v2-cicd"
run-name: Slack Bot CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
    - 'helm/**'
    - '.github/**'

concurrency:
    group: slack-api
    cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Github actions Checkout
      uses: actions/checkout@v4.1.7

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.4.0

    - name: Get version
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.4.1
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ secrets.DOCKER_USERNAME}}/baekjoon-slack-bot:ver-${{ steps.image.outputs.version }}

