name: "baekjoon-slack-bot-PR"
run-name: Slack Bot PR

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
    - '.github/**'
    - 'assets/**'
    - 'docs/**'
    - 'helm/**'

concurrency:
    group: baekjoon-pr
    cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run unit tests
        run: make unit
      
      - name: Build test
        run: make build
