name: "baekjoon-slack-bot-cicd"
run-name: Slack Bot CI/CD Pipeline

on:
  push:
    branches: ["main"]
    paths-ignore:
    - 'helm/**'
    - '.github/**'

concurrency:
    group: slack-api
    cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Github actions Checkout
      uses: actions/checkout@v4.1.7

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.4.0

    - name: Get version
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.4.1
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ secrets.DOCKER_USERNAME}}/baekjoon-slack-bot:ver-${{ steps.image.outputs.version }}

  CD:
    runs-on: ubuntu-latest
    needs: CI
    concurrency:
      group: modify-helm
      cancel-in-progress: false

    steps:
    - name: Get version
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: setup-yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
        sudo chmod +x /usr/bin/yq

    - name: Checkout helm repository
      uses: actions/checkout@v4.1.7
      with:
        repository: synoti21/baekjoon-slack-bot
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Modify Helm values.yaml using yq
      run: |
        cd helm
        export VERSION=${{ steps.image.outputs.version }}
        yq e '.image.tag = "ver-" + env(VERSION)' -i values.yaml

    - name: Commit and push the updated manifest
      run: |
        cd helm
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git commit -am ":construction_worker: chore: Update deployment to ${{ steps.image.outputs.version }}"
        git push